# Package Overview
package_name: sentiment_model

# Data Files
training_data_file: Reviews.csv

# Variables
# The variable we are attempting to predict (cnt)
target: Sentiment

model_name: sentiment_model
model_save_file: sentiment__model_output_v

# Features that will go inside processing pipeline
features:
  - Text
  
unused_fields:  # Features to drop before pipeline
  - Id
  - HelpfulnessNumerator
  - HelpfulnessDenominator

  
# Set train/test split
test_size: 0.2

# Set the random seed
random_state: 0

# Alogrithm parameters
batch_size: 128
epochs: 1
